[package]
name = "call_c_from_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall_double = "0.2.1"
mockall = "0.11.2"

[dev-dependencies]
