name: Rust CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt-get install ninja-build
          cargo install cbindgen

      - name: Advent of Code 2021
        working-directory: ${{github.workspace}}/aoc/2021
        run: |
          cargo build
          cargo test
          cargo run --release

      - name: Advent of Code 2022
        working-directory: ${{github.workspace}}/aoc/2022
        run: |
          cargo build
          cargo test
          cargo run --release

      - name: Advent of Code 2023
        working-directory: ${{github.workspace}}/aoc/2023
        run: |
          cargo build
          cargo test
          cargo run --release

      - name: FFI, Call C from Rust
        working-directory: ${{github.workspace}}/ffi/call_c_from_rust
        run: |
          cargo test
          cargo run --release

      - name: FFI, Call Rust from C
        working-directory: ${{github.workspace}}/ffi/call_rust_from_c
        run: |
          cmake -B build -G Ninja
          cmake --build build
          ./build/call_rust_from_c_example
